if data[:8] == 'OMSI0001': 
    #Code omitted for clarity...
    fields = data.split('\0')
    #...
    lFileName = fields[1]
    #...
    lIsExecuted = self.receiveFile(pClientSocket, lFileName, lStudentEmail)
